server:
  port: 8001 #该 Module 的端口号

feign:
  httpclient:
    enabled: true # 支持httpClient开关
    max-connections: 200 # 最大连接数
    max-connections-per-route: 20 # 单个路径最大连接数

# nacos配置
spring:
  application:
#    name: server-provide
      name: server-consumer # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        cluster-name: CS

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Hongkong
    username: root
    password: 123456
    druid:
      #      # 主库数据源
      #      master:
      #        url: jdbc:mysql://101.132.108.91:3307/hk_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=Hongkong
      #        username: hk
      #        password: hk2021
      #      # 从库数据源
      #      slave:
      #        # 从数据源开关/默认关闭
      #        enabled: false
      #        url:
      #        username:
      #        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: huike
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

#数据库配置
mybatis:
  # 搜索指定包别名
  type-aliases-package: com.sut.cloud.domain.vo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis/mybatis-config.xml
  # 开启驼峰命名规则
  configuration:
    map-underscore-to-camel-case: true

  # MyBatis-plus
  mybatis-plus:
    mapper-locations: classpath:mapper/**/*Mapper.xml
    type-aliases-package: com.myspring.study.mapper

