server:
  port: 7001 #该 Module 的端口号

# nacos配置
spring:
  application:
    name: server-provide # 服务名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: common # 集群名称

  # RabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest